// Default values for the entire dashboard form state
import type { DashboardState } from "@shared/schema";

export const DEFAULT_CAPABILITIES = {
  level37: `ASAM 3.7 (Medically Monitored Intensive Inpatient): 24/7 registered nursing; 24/7 on-call psychiatrist and addiction medicine physician; on-site prescribing; full medical detox capacity including CIWA-Ar-guided alcohol/benzo withdrawal management, COWS-guided opioid withdrawal management, and buprenorphine induction; continuous vital sign monitoring; on-site laboratory; co-occurring psychiatric stabilization; individual and group SUD and psychiatric therapy; milieu-based treatment; case management and discharge planning; locked inpatient unit with 24-hour observation.`,
  level35: `ASAM 3.5 (Clinically Managed High-Intensity Residential): 24-hour structured milieu with 24/7 counseling and nursing staff; daily psychiatric and medical oversight; structured group and individual SUD and behavioral health treatment; evidence-based relapse prevention; MAT continuation; co-occurring psychiatric management for stable, non-acute presentations; case management, family engagement, and community reintegration planning; discharge and aftercare coordination.`,
};

// Helper to create a blank-note version for every boolean field
const n = ""; // blank note default

export const DEFAULT_STATE: DashboardState = {
  config: {
    levelOfCare: "3.7",
    editionLanguage: "3rd",
    outputType: "both",
    ncMedicaid: true,
    geminiApiKey: import.meta.env.VITE_GEMINI_API_KEY ?? "",
    patientDescriptor: "",
    patientAge: null,
    patientGender: null,
    patientDescriptorAddendum: "",
  },
  capabilities: DEFAULT_CAPABILITIES,
  dimensions: {
    d1Core: {
      riskRating: 0, comments: "",
      activeIntoxication: false, activeIntoxicationNote: n,
      activeWithdrawal: false, activeWithdrawalNote: n,
      polySubstanceUse: false, polySubstanceUseNote: n,
      historyOfDTs: false, historyOfDTsNote: n,
      historyOfWithdrawalSeizures: false, historyOfWithdrawalSeizuresNote: n,
      ciwaScore: "", cowsScore: "",
      alcoholPrimary: false, alcoholPrimaryNote: n,
      opioidPrimary: false, opioidPrimaryNote: n,
      benzodiazepinePrimary: false, benzodiazepinePrimaryNote: n,
      stimulantPrimary: false, stimulantPrimaryNote: n,
      cannabisPrimary: false, cannabisPrimaryNote: n,
      requiresDetoxPharmacology: false, requiresDetoxPharmacologyNote: n,
      requiresMedicalMonitoring: false, requiresMedicalMonitoringNote: n,
      ivFluidOrPressor: false, ivFluidOrPressorsNote: n,
    },
    d1Extra: {
      comments: "",
      chronicHeavyUse: false, chronicHeavyUseNote: n,
      lastUseRecent: false, lastUseRecentNote: n,
      priorDetoxMultiple: false, priorDetoxMultipleNote: n,
      neurologicVulnerability: false, neurologicVulnerabilityNote: n,
      nutritionalDeficiency: false, nutritionalDeficiencyNote: n,
      motivatedForDetox: false, motivatedForDetoxNote: n,
      agreedToMedication: false, agreedToMedicationNote: n,
    },
    d2Core: {
      riskRating: 0, comments: "",
      activeMedicalCondition: false, activeMedicalConditionNote: n,
      requiresDailyNursingMonitoring: false, requiresDailyNursingMonitoringNote: n,
      requiresLabOrVitalMonitoring: false, requiresLabOrVitalMonitoringNote: n,
      infectiousDisease: false, infectiousDiseaseNote: n,
      hepaticDisease: false, hepaticDiseaseNote: n,
      cardiovascularDisease: false, cardiovascularDiseaseNote: n,
      diabetesOrMetabolicCondition: false, diabetesOrMetabolicConditionNote: n,
      pregnancyOrPostpartum: false, pregnancyOrPostpartumNote: n,
      recentHospitalization: false, recentHospitalizationNote: n,
      medicationManagementNeeded: false, medicationManagementNeededNote: n,
    },
    d2Extra: {
      comments: "",
      chronicPainContributing: false, chronicPainContributingNote: n,
      painDrivingSubstanceUse: false, painDrivingSubstanceUseNote: n,
      poorNutritionOrHydration: false, poorNutritionOrHydrationNote: n,
      poorADLsFromMedicalCondition: false, poorADLsFromMedicalConditionNote: n,
      sleepDisorderPresent: false, sleepDisorderPresentNote: n,
      priorODOrNaloxoneUse: false, priorODOrNaloxoneUseNote: n,
    },
    d3Core: {
      riskRating: 0, comments: "",
      activeSuicidalIdeation: false, activeSuicidalIdeationNote: n,
      recentSuicideAttempt: false, recentSuicideAttemptNote: n,
      activeHomicidalIdeation: false, activeHomicidalIdeationNote: n,
      activePsychosis: false, activePsychosisNote: n,
      activeMania: false, activeManiaNote: n,
      severeMoodDisturbance: false, severeMoodDisturbanceNote: n,
      severeAnxietyOrPanic: false, severeAnxietyOrPanicNote: n,
      impairedSelfCare: false, impairedSelfCareNote: n,
      impairedRealityTesting: false, impairedRealityTestingNote: n,
      gravityDisabilityPresent: false, gravityDisabilityPresentNote: n,
      diagnosedMDD: false, diagnosedMDDNote: n,
      diagnosedBipolar: false, diagnosedBipolarNote: n,
      diagnosedSchizophreniaSpectrum: false, diagnosedSchizophreniaSpectrumNote: n,
      diagnosedPTSD: false, diagnosedPTSDNote: n,
      diagnosedADHD: false, diagnosedADHDNote: n,
      diagnosedPersonalityDisorder: false, diagnosedPersonalityDisorderNote: n,
      requiresPsychMedManagement: false, requiresPsychMedManagementNote: n,
      requiresPsychiatricMonitoring: false, requiresPsychiatricMonitoringNote: n,
    },
    d3Extra: {
      comments: "",
      traumaHistoryPresent: false, traumaHistoryPresentNote: n,
      childhoodAdversity: false, childhoodAdversityNote: n,
      acutePsychosocialStressor: false, acutePsychosocialStressorNote: n,
      griefOrLossRecent: false, griefOrLossRecentNote: n,
      cognitiveImpairmentPresent: false, cognitiveImpairmentPresentNote: n,
      intellectualDisabilityPresent: false, intellectualDisabilityPresentNote: n,
      substanceInducedPsychiatric: false, substanceInducedPsychiatricNote: n,
      primaryPsychiatricIndependent: false, primaryPsychiatricIndependentNote: n,
      psychiatricTreatmentEngaged: false, psychiatricTreatmentEngagedNote: n,
      insightIntoMentalIllness: false, insightIntoMentalIllnessNote: n,
    },
    d4Core: {
      riskRating: 0, comments: "",
      stagePrecontemplation: false, stagePrecontemplationNote: n,
      stageContemplation: false, stageContemplationNote: n,
      stagePreparation: false, stagePreparationNote: n,
      stageAction: false, stageActionNote: n,
      deniesToHaveProblem: false, deniesToHaveProblemNote: n,
      ambivalentAboutTreatment: false, ambivalentAboutTreatmentNote: n,
      externalPressureOnly: false, externalPressureOnlyNote: n,
      refusedMedicationAssistedTreatment: false, refusedMedicationAssistedTreatmentNote: n,
      limitedInsightIntoSeverity: false, limitedInsightIntoSeverityNote: n,
    },
    d4Extra: {
      comments: "",
      motivationalInterviewingTargeted: false, motivationalInterviewingTargetedNote: n,
      historicalEngagementPoor: false, historicalEngagementPoorNote: n,
      cognitiveBarriersToEngagement: false, cognitiveBarriersToEngagementNote: n,
      culturalOrLanguageBarrier: false, culturalOrLanguageBarrierNote: n,
      selfIdentifiesNeedForHelp: false, selfIdentifiesNeedForHelpNote: n,
      familyPressurePositive: false, familyPressurePositiveNote: n,
      spiritualOrValueBasedMotivation: false, spiritualOrValueBasedMotivationNote: n,
    },
    d5Core: {
      riskRating: 0, comments: "",
      multiplePriorTreatmentEpisodes: false, multiplePriorTreatmentEpisodesNote: n,
      relapsedFromPriorLevel: false, relapsedFromPriorLevelNote: n,
      priorASAM37Admission: false, priorASAM37AdmissionNote: n,
      priorASAM35Admission: false, priorASAM35AdmissionNote: n,
      priorDetoxOnlyNoFollowup: false, priorDetoxOnlyNoFollowupNote: n,
      cravingsHighAtAdmission: false, cravingsHighAtAdmissionNote: n,
      triggerRichEnvironment: false, triggerRichEnvironmentNote: n,
      coOccurringDisorderUntreated: false, coOccurringDisorderUntreatedNote: n,
      lackOfCopingSkills: false, lackOfCopingSkillsNote: n,
      dailyOrNearDailyUse: false, dailyOrNearDailyUseNote: n,
      useToPreventWithdrawal: false, useToPreventWithdrawalNote: n,
    },
    d5Extra: {
      comments: "",
      kindlingOrProgressivePatternPresent: false, kindlingOrProgressivePatternPresentNote: n,
      behavioralAddictionConcurrent: false, behavioralAddictionConcurrentNote: n,
      priorODHighRiskPattern: false, priorODHighRiskPatternNote: n,
      lowFrustrationTolerance: false, lowFrustrationToleranceNote: n,
      priorSuccessfulRecovery: false, priorSuccessfulRecoveryNote: n,
      longCleanTimeInPast: false, longCleanTimeInPastNote: n,
      relapseWarningSignsIdentified: false, relapseWarningSignsIdentifiedNote: n,
    },
    d6Core: {
      riskRating: 0, comments: "",
      homelessOrUnstableHousing: false, homelessOrUnstableHousingNote: n,
      livesWithActiveSubstanceUsers: false, livesWithActiveSubstanceUsersNote: n,
      lacksFamilyOrSocialSupport: false, lacksFamilyOrSocialSupportNote: n,
      unsafeOrAbusiveHomeEnvironment: false, unsafeOrAbusiveHomeEnvironmentNote: n,
      unemployedOrFinancialInstability: false, unemployedOrFinancialInstabilityNote: n,
      legalIssuesPending: false, legalIssuesPendingNote: n,
      childProtectiveServicesInvolved: false, childProtectiveServicesInvolvedNote: n,
      transportationBarrier: false, transportationBarrierNote: n,
      noAftercarePlanInPlace: false, noAftercarePlanInPlaceNote: n,
      priorDischargeAMAOrExpelled: false, priorDischargeAMAOrExpelledNote: n,
    },
    d6Extra: {
      comments: "",
      peerSupportOrSponsorPresent: false, peerSupportOrSponsorPresentNote: n,
      familySystemEngagedInTreatment: false, familySystemEngagedInTreatmentNote: n,
      insuranceOrBenefitBarrier: false, insuranceOrBenefitBarrierNote: n,
      culturalOrMinorityStressor: false, culturalOrMinorityStressorNote: n,
      sober_supportNetwork: false, sober_supportNetworkNote: n,
      stableHousingAtDischarge: false, stableHousingAtDischargeNote: n,
      employerSupportive: false, employerSupportiveNote: n,
    },
  },
};
